---
include:
  - path: compose.d/pg-instance.yaml
    project_directory: .
  - path: compose.d/pg-helper-agent.yaml
    project_directory: .
  - path: compose.d/pg-helper.yaml
    project_directory: .
