---
include:
  - compose.d/pg-instance.yaml
  - compose.d/pg-helper-agent.yaml
  - compose.d/pg-helper.yaml
  - compose.d/pg-waiter.yaml

secrets:
  JWT_SECRET:
    file: "./tests/secrets/JWT_SECRET"
  SESSION_SECRET:
    file: "./tests/secrets/SESSION_SECRET"
  STORAGE_ENCRYPTION_KEY:
    file: "./tests/secrets/STORAGE_ENCRYPTION_KEY"

services:
  authelia:
    container_name: "authelia"
    image: "docker.io/authelia/authelia:latest"
    restart: "unless-stopped"
    secrets:
      - JWT_SECRET
      - SESSION_SECRET
      - STORAGE_ENCRYPTION_KEY
      - db_owner_authelia
    environment:
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: "/run/secrets/JWT_SECRET"
      AUTHELIA_SESSION_SECRET_FILE: "/run/secrets/SESSION_SECRET"
      AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE: "/run/secrets/db_owner_authelia"
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: "/run/secrets/STORAGE_ENCRYPTION_KEY"
    volumes:
      - "./tests/authelia/config:/config"
    depends_on:
      pg-waiter-authelia:
        condition: service_healthy
        required: true
    profiles:
      - authelia
