gen-key:
  public-key: "e2e/secrets/pg_helper_e2e_pg_helper_jwt_public_key"
  private-key: "e2e/secrets/pg_helper_e2e_pg_helper_jwt_key"

gen-jwt:
  signer: "e2e/secrets/pg_helper_e2e_pg_helper_jwt_key"
  duration: "2160h"
  audiences:
    - "pg-helper-web"
    - "pg-helper-grpc"
    - "pg-helper"
