---
log-level: debug

serve:
  web:
    enabled: true
    tls:
      enabled: false
    auth:
      jwt:
        enabled: true
        audience: pg-helper
        verify-key:
          types:
            - EdDSA
          files:
            - "/run/secrets/pg_helper_e2e_pg_helper_jwt_public_key"
  grpc:
    port: 8443
    tls:
      enabled: false

    auth:
      jwt:
        enabled: true
        audience: pg-helper
        verify-key:
          types:
            - EdDSA
          files:
            - "/run/secrets/pg_helper_e2e_pg_helper_jwt_public_key"
  source:
    file:
      enabled: true
      file-paths:
        - "/etc/pg-helper/sources/"
