---
name: Pull Request
on:
  pull_request:
    branches:
      - main
      - "release-*"

jobs:
  call-workflow-build:
    uses: a-light-win/pg-helper/.github/workflows/reusable/build.yaml@main
  call-workflow-e2e-test:
    uses: a-light-win/pg-helper/.github/workflows/reusable/e2e-test.yaml@main
    if: false
    needs:
      - call-workflow-build
