---
name: Pull Request
on:
  pull_request:
    branches:
      - main
      - "release-*"
  merge_group:

jobs:
  call-workflow-build:
    uses: a-light-win/pg-helper/.github/workflows/_build.yaml@main
  call-workflow-e2e-test:
    uses: a-light-win/pg-helper/.github/workflows/_e2e-test.yaml@main
    if: false
    needs:
      - call-workflow-build
