---
on:
  pull_request:
    branches:
      - main
      - "release-*"

env:
  GOPATH: "$HOME/go"
  GOCACHE: "$HOME/go/cache"
  GOBIN: "/usr/local/bin"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup just
        uses: extractions/setup-just@v2

      - name: cache go
        uses: actions/cache@v2
        with:
          path: ~/go
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        run: |
          just --unstable dev build
          tar -cf pg-helper.tar dist/pg-helper

      - name: Unit Test
        run: |
          just --unstable dev test

      - name: check test coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          config: ./.testcoverage.yaml

      - name: Upload pg-helper
        uses: actions/upload-artifact@v4
        with:
          name: pg_helper_bin
          path: pg-helper.tar
          retention-days: 7
          compression-level: 0
  e2e:
    # Disable e2e test now
    # the podman in ubuntu 22.04 is not working, It may be too old?
    # Try again after ubuntu 24.04 is available
    if: false
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup just
        uses: extractions/setup-just@v2

      - name: Download pg-helper
        uses: actions/download-artifact@v4
        with:
          name: pg_helper_bin

      - name: Extract pg-helper
        run: |
          tar -xf pg-helper.tar

      - name: Setup e2e environment
        run: |
          just --unstable setup e2e-env

      - name: Run e2e tests
        run: |
          just --unstable e2e

      - name: Archive e2e test results
        if: always()
        run: |
          tar -cf e2e-results.tar e2e/output

      - name: Upload e2e test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-results
          path: e2e-results.tar
          retention-days: 7
