---
name: Pull Request
on:
  pull_request:
    branches:
      - main
      - "release-*"

jobs:
  call-workflow-build:
    uses: ./.github/workflows/_build.yaml@main
  call-workflow-e2e-test:
    uses: ./.github/workflows/_e2e-test.yaml@main
    if: false
    needs:
      - call-workflow-build
