---
on:
  pull_request:
    branches:
      - main
      - "release-*"

env:
  GOPATH: "$HOME/go"
  GOCACHE: "$HOME/go/cache"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup just
        uses: extractions/setup-just@v2

      - name: cache go
        uses: actions/cache@v2
        with:
          path: ~/go
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        run: |
          just --unstable dev build

      - name: Unit Test
        run: |
          just --unstable dev test

      - name: check test coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          config: ./.testcoverage.yaml
