---
on:
  push:
    tags:
      - "v*"

jobs:
  call-workflow-build:
    uses: a-light-win/pg-helper/.github/workflows/_build.yaml@main
  call-workflow-e2e-test:
    if: false
    needs:
      - call-workflow-build
    uses: a-light-win/pg-helper/.github/workflows/_e2e-test.yaml@main
  call-workflow-build-image:
    needs:
      - call-workflow-e2e-build
      - call-workflow-e2e-test
    uses: a-light-win/pg-helper/.github/workflows/_build-image.yaml@main
  # TODO: Add release to GitHub
