---
name: Release Branches
on:
  push:
    branches:
      - main
      - "release-*"

jobs:
  # Run build after pull request merged so we can:
  #
  # 1. reuse the go cache in later pull requests
  # 2. get the latest code coverage of branches
  call-workflow-build:
    uses: ./.github/workflows/_build.yaml@main
