---
on:
  push:
    tags:
      - "v*"

jobs:
  call-workflow-build:
    uses: a-light-win/pg-helper/.github/workflows/reusable/build.yaml@main
  call-workflow-e2e-test:
    needs:
      - call-workflow-build
    uses: a-light-win/pg-helper/.github/workflows/reusable/build.yaml@main
  call-workflow-build-image:
    needs:
      - call-workflow-e2e-test
    uses: a-light-win/pg-helper/.github/workflows/reusable/build-image.yaml@main
  # TODO: Add release to GitHub
