---
services:
  authelia:
    container_name: "authelia"
    image: authelia:latest
    build:
      context: .
      dockerfile: Dockerfile.authelia
    entrypoint:
      - "/bin/sh"
      - "/app/pg-waiter.sh"
      - authelia
      - pg-13
      - /app/entrypoint.sh
    restart: "unless-stopped"
    secrets:
      - jwt_secret
      - session_secret
      - storage_encryption_key
      - db_owner_authelia
      - auth_token_pg_waiter
    environment:
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: "/run/secrets/jwt_secret"
      AUTHELIA_SESSION_SECRET_FILE: "/run/secrets/session_secret"
      AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE: "/run/secrets/db_owner_authelia"
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: "/run/secrets/storage_encryption_key"
      PG_HELPER_TOKEN_FILE: "/run/secrets/auth_token_pg_waiter"
      PG_HELPER_URL: "http://pg-helper:8080"
    volumes:
      - "./config/authelia/config:/config"
    profiles:
      - authelia

secrets:
  jwt_secret:
    file: "./secrets/authelia/jwt_secret"
  session_secret:
    file: "./secrets/authelia/session_secret"
  storage_encryption_key:
    file: "./secrets/authelia/storage_encryption_key"
  db_owner_authelia:
    file: "./secrets/pg-helper/db_owner_authelia"
  auth_token_pg_waiter:
    file: "./secrets/authelia/auth_token_pg_waiter"
