---
services:
  authelia:
    container_name: "authelia"
    image: authelia:latest
    build:
      context: .
      dockerfile: dockerfile.d/Dockerfile.authelia
    entrypoint:
      - "/bin/sh"
      - "/app/pg-waiter.sh"
      - authelia
      - pg-13
      - /app/entrypoint.sh
    restart: "unless-stopped"
    secrets:
      - source: pg_helper_e2e_authelia_jwt_secret
        mode: "0440"
      - source: pg_helper_e2e_authelia_session_secret
        mode: "0440"
      - source: pg_helper_e2e_authelia_storage_encryption_key
        mode: "0440"
      - source: pg_helper_e2e_authelia_db_owner
        mode: "0440"
      - source: pg_helper_e2e_authelia_pg_waiter
        mode: "0440"
    environment:
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: "/run/secrets/pg_helper_e2e_authelia_jwt_secret"
      AUTHELIA_SESSION_SECRET_FILE: "/run/secrets/pg_helper_e2e_authelia_session_secret"
      AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE: "/run/secrets/pg_helper_e2e_authelia_db_owner"
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: "/run/secrets/pg_helper_e2e_authelia_storage_encryption_key"
      PG_HELPER_TOKEN_FILE: "/run/secrets/pg_helper_e2e_authelia_pg_waiter"
      PG_HELPER_URL: "http://pg-helper:8080"
    volumes:
      - "./config/authelia/config:/config"
    profiles:
      - authelia

secrets:
  pg_helper_e2e_authelia_jwt_secret:
    external: true
  pg_helper_e2e_authelia_session_secret:
    external: true
  pg_helper_e2e_authelia_storage_encryption_key:
    external: true
  pg_helper_e2e_authelia_pg_waiter:
    external: true
